config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  post 'generate_recommendations', to: 'home#recommendations'
  get 'recommendations', to: 'home#recommendations_template'

  root "home#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def recommendations
    Rails.logger.info("Selected genres: #{params[:genres]}")

    prompt = "Give me 5 short film recommendations that fit all or some of the following genres: #{params[:genres].join(', ')}. "\
      "Return this response as a json array of recommendation. Each recommendation should have only 2 keys: title and description. "\
      "Include no other commentary in the response."

    response = OpenAI::Client.new.chat(
      parameters: {
          model: "gpt-3.5-turbo", # Required.
          messages: [{ role: "user", content: prompt}], # Required.
          temperature: 0.7,
      })
    tokens_used = response['usage']['total_tokens']
    recos_raw = response.dig("choices", 0, "message", "content")

    # tokens_used = 400
    # recos_raw = "\n\n[\n  {\n    \"title\": \"The Gunfighter\",\n    \"description\": \"A gunslinger walks into a saloon and finds himself in a deadly game of cat and mouse.\",\n    \"url\": \"https://vimeo.com/72545203\"\n  },\n  {\n    \"title\": \"The Adventures of Indiana Jones\",\n    \"description\": \"A parody of the Indiana Jones films, featuring an unlikely hero on a quest for treasure.\",\n    \"url\": \"https://www.youtube.com/watch?v=VufilzHKTqk\"\n  },\n  {\n    \"title\": \"Death in Bloom\",\n    \"description\": \"A surreal dark comedy about a man who finds himself trapped in a nightmarish garden.\",\n    \"url\": \"https://vimeo.com/146789055\"\n  },\n  {\n    \"title\": \"Kung Fury\",\n    \"description\": \"A martial arts master travels through time to stop Hitler and his army of kung-fu Nazis.\",\n    \"url\": \"https://www.youtube.com/watch?v=bS5P_LAqiVg\"\n  },\n  {\n    \"title\": \"The Voorman Problem\",\n    \"description\": \"A psychiatrist is called to a prison to evaluate a patient who believes he is a god.\",\n    \"url\": \"https://vimeo.com/70160643\"\n  }\n]"

    @recos = JSON.parse(recos_raw)

    Rails.logger.info("GPT recommendations: #{recos_raw}")
    Rails.logger.info("Tokens used: #{tokens_used}")
  end

  def recommendations_template
    recos_raw = "\n\n[\n  {\n    \"title\": \"The Gunfighter\",\n    \"description\": \"A gunslinger walks into a saloon and finds himself in a deadly game of cat and mouse.\",\n    \"url\": \"https://vimeo.com/72545203\"\n  },\n  {\n    \"title\": \"The Adventures of Indiana Jones\",\n    \"description\": \"A parody of the Indiana Jones films, featuring an unlikely hero on a quest for treasure.\",\n    \"url\": \"https://www.youtube.com/watch?v=VufilzHKTqk\"\n  },\n  {\n    \"title\": \"Death in Bloom\",\n    \"description\": \"A surreal dark comedy about a man who finds himself trapped in a nightmarish garden.\",\n    \"url\": \"https://vimeo.com/146789055\"\n  },\n  {\n    \"title\": \"Kung Fury\",\n    \"description\": \"A martial arts master travels through time to stop Hitler and his army of kung-fu Nazis.\",\n    \"url\": \"https://www.youtube.com/watch?v=bS5P_LAqiVg\"\n  },\n  {\n    \"title\": \"The Voorman Problem\",\n    \"description\": \"A psychiatrist is called to a prison to evaluate a patient who believes he is a god.\",\n    \"url\": \"https://vimeo.com/70160643\"\n  }\n]"
    @recos = JSON.parse(recos_raw)

    render "recommendations"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
- genres = ["Action", "Adventure", "Animation", "Biography", "Black-Comedy", "Comedy", "Crime", "Cult-classic", "Documentary", "Drama", "Experimental", "Fairy-tale", "Futuristic", "Historical", "Horror", "Melodrama", "Musical", "Mystery", "Noir", "Political", "Psychological", "Romance", "Satire", "Sci-Fi & Fantasy", "Slapstick", "Social-issue", "Sports", "Superhero", "Thriller", "War"]

.px-4.py-5.text-center
  %h1.display-5.fw-bold Entertain Me!
  .col-lg-6.mx-auto
    %p.lead.mb-4 Your entertainment, personalized by AI

= form_with url: generate_recommendations_path, method: :post, data: { turbo: false } do |form|
  .row.row-cols-1.row-cols-md-6.g-4
    = form.collection_check_boxes(:genres, genres, :to_s, :to_s, include_hidden: false) do |cb|
      .col
        .card
          .card-body
            = cb.label class: "d-inline-flex gap-3" do
              = cb.check_box class: 'form-check-input', style: "font-size: 1.375em;"
              %span.pt-1.form-checked-content= cb.value

  .row.mt-4.mb-4.text-center
    .col.align-self-center
      = form.submit "Entertain Me!", class: 'btn btn-primary btn-lg', onClick: "this.form.submit(); this.disabled=true; this.value='Good things take time, great things take a little longer...';"

app/views/home/recommendations.html.haml
.px-4.pt-4.text-center
  .col-lg-6.mx-auto
    %p.lead Short films for you, recommended by AI

.row
  .col
    - @recos.each do |reco|
      .card.my-2.rounded-5
        .card-body
          %h6.mb-0= reco['title']
          %p.mb-0.opacity-75= reco['description']
          = link_to "Search on YouTube", "https://www.youtube.com/results?#{{search_query: reco['title']}.to_param}", target: "_blank"

.row.pt-4
  .col.text-center
    = link_to "Try again", root_path, class: 'mx-auto'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Entertain Me
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .container-md
      = yield